---
title: "R-AI-D (R AI Distrobox) - Rtificially Intelligent Sound Analysis and Synthesis"
output: github_document
bibliography: "REFERENCES.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

R-AI-D is a [Distrobox](https://distrobox.it/ "Distrobox documentation") pet
container for artificially intelligent sound analysis and synthesis. R-AI-D is
based on the [Rocker "Resolute Raccoon" r2u container
image](https://github.com/rocker-org/r2u). R-AI-D features:

- the [Ubuntu 26.04 LTS "Resolute 
Raccoon"](https://help.ubuntu.com/ "Ubuntu help") operating system,
- the R programming language [@r-base],
- [r2u: CRAN as Ubuntu Binaries](https://eddelbuettel.github.io/r2u/ "r2u: CRAN
  as Ubuntu Binaries") 
- bspm: Bridge to System Package Manager [@ucar2026],
- [RStudio Desktop daily build](https://docs.posit.co/ide/user/ "RStudio
  documentation"),
- the [Quarto](https://quarto.org/ "Quarto home page") scientific and technical
  publishing system,
- R packages for package development [@wickham2023r],
- R packages for interfacing with AI tools [@verdearregoitia2026llmsr]:
    - ellmer [@wickham2026],
    - mcptools [@couch2026m],
    - ollamar [@lin2026o],
    - ragnar [@kalinowski2026r],
    - shinychat [@cheng2026s],
    - vitals [@couch2026v],
- R packages for sound analysis and synthesis [@sueur2018sound],
- the
  [Faust](https://github.com/grame-cncm/faust/blob/master-dev/documentation/faust-quick-reference.pdf
  "Faust Quick Reference (PDF)") functional programming language for sound
  synthesis and audio processing,
- the [Ollama](https://docs.ollama.com/ "Ollama Documentation") framework for
  managing local models, and
- a modern command line, including Ollama-supported coding assistants.

R-AI-D was developed on
[Bluefin DX](https://projectbluefin.io "Bluefin home page"), but should run on
any Linux host system supporting Distrobox. I test on a Raspberry Pi 5, and the
release includes scripts that should work on any recent Debian or Ubuntu host.
On `x86_64` systems, an NVIDIA GPU will be detected and used automatically.

Like its Bluefix DX inspiration, the R-AI-D command line features
[Homebrew](https://brew.sh/ "Homebrew home page") and the
[Starship](https://starship.rs/ "Starship home page") cross-shell prompt
generator. The
[Cascaydia Cove nerd font](https://www.nerdfonts.com/ "nerd font aggregator")
is included and other nerd fonts are available. The Ollama-launchable coding
assistants [OpenCode](https://opencode.ai/ "OpenCode home page"),
[Codex CLI](https://developers.openai.com/codex/cli "Codex CLI documentation"),
and [Claude CLI](https://www.claudecli.org/ "Claude CLI home page") are also
included.

## Licensing, contributing, roadmap, etc.

R-AI-D uses the
[Creative Commons CC0](https://creativecommons.org/public-domain/cc0/ "CC0
license text") license, which is a bunch of words that say mostly "R-AI-D is
public domain." R-AI-D is just some `bash` scripts that download some open
source software and build it into a container. Why would I copyright
that?

Contributing? Forks,
[bug reports and feature
requests](https://github.com/AlgoCompSynth/R-AI-D/issues/new "open an issue")
are welcome. Pull requests, on the other hand, probably not. I don't have the
time to review other peoples' code beyond fixing typos.

The roadmap is mostly determined by what I need and when. The only
feature I want to add is a "native" port to Ubuntu running in Windows
Subsystem for Linux. Hosting setup scripts for Fedora, CentOS Stream,
Arch Linux and openSUSE Tumbleweed are easy to do but I have no need
for them. If you do, open an issue and I'll put them in.

Later in my exploration of AI I will probably need some AI engineering
tools like JupyterLab, PyTorch, and CUDA, but the image is pretty big
already, so I won't add them until I need them. And R AI packages cover a lot
of the bases already, such as interfacing with Ollama and other local LLM tools,
retrieval augmented generation (RAG), and model context protocol (MCP).

## Building the Image and Container

See [container-creation/README-Building-the-Image-and-Container.md](container-creation/README-Building-the-Image-and-Container.md)

## References
