---
title: "Building the Image and Container"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This directory contains scripts for building the R-AI-D image and
container.

## Prerequisites

- Podman 4.9.3 or later installed on your system. R-AI-D was developed
  on [Bluefin
  DX](https://projectbluefin.io "Bluefin Project Home Page"), which has
  the hosting built in, but Podman is available in most current Linux
  distributions. The oldest host I test on is Ubuntu 24.04 LTS "Noble
  Numbat", which has Podman 4.9.3.
- If your host has an NVIDIA GPU, you will need the drivers and the
  NVIDIA Container Toolkit installed. The R-AI-D image / container build
  script will detect the GPU and install the required software. The GPU
  must be GTX 16xx or later. I do not have any AMD GPUs or CPUs to test
  on, so there is no code to support them other than what Ollama
  provides.
- Sufficient disk space for container images. The current image requires
  about 7.2 gigabytes. You will also need to have space for all of the
  models you will be downloading to disk.

## Build Process

### 1. Edit environment variables

There are a number of environment variables that control the building of
the image and container. They are set in the file
`set_container_envars`. Most of them can be left as is, but there is one
you will need to attend to:

- `FORCE_CPU`: This is commented out in `set_container_envars`. If you
  uncomment the setting, it will set `FORCE_CPU="FORCE_CPU"`, and the
  container will be built using the CPU only, even if you have a GPU.
  This is useful if your CPU has more RAM than your GPU and you want to
  use a model larger than what your GPU VRAM can hold.

### 2. Build image

``` bash
./1_build_image.sh
```

This script builds the base container image that includes:

- Ubuntu 26.04.LTS "Resolute Raccoon",
- R package development environment - RStudio Server, the Bridge to
  System Package Manager, Quarto, and AI interface R packages,
- the Faust functional audio stream compiler,
- R library packages for audio analysis and synthesis,
- OLLAMA AI tools, and
- the `r-ai-d` administrator account with initial password `r-ai-d`.

The image is named `localhost/r-ai-d-base:latest`\

### 3. Create and run the container

``` bash
./2_replace_and_run_container.sh
```

This creates a container named `R-AI-D-CUDA` or `R-AI-D-CPU`, depending
on which compute mode was specified when the image was built. Any
existing container with that name will be deleted.

``` bash
R-AI-D-CPU
```

depending on whether you have an NVIDIA GPU or not. When you enter the
container, you will be at the container command line in the
***container*** home directory.
